import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/react-query-provider";
import TopBar from "@/components/nav/top-bar";

const nunitoSans = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable}  max-w-7xl mx-auto antialiased`}>
        <TopBar />
        <ReactQueryClientProvider>
          <div className="mt-[8vh]">{children}</div>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
